graphqlSchema:
  files: '*.graphql'
jsResource:
  files: './resources.js'
'@harperdb/nextjs':
  package: '@harperdb/nextjs'
  files: '/*'
'@harperdb/http-cache':
  package: '@harperdb/http-cache'
  files: '/*'
